[features]
seeds = true
skip-lint = false
[programs.localnet]
lootbox_program = "6z8MAxuUCZxEqyXnb9xHoGYt5wmpUS6G2hhSho48h1GZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
