[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "7X136wosjGtZXSQjnsf7qXbENUWAYrRGPppYdPVv3Z4E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
testNFT = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
